name: Update KML

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python alert.py  # Replace with your script name

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the token from secrets
        run: |
          git config --local user.email "jeandeauxmail@gmail.com"
          git config --local user.name "jeandeauxmail-cell"
          git add alerts.kml
          git commit -m "Update KML file"
          git push https://$GITHUB_TOKEN@github.com/jeandeauxmail-cell/alertstest.git HEAD:main
