name: Build & Publish CAP → KML


on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes


permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


      - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'


    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Generate KML
    run: |
      mkdir -p site
      python src/generate_kml.py site/alerts.kml


    - name: Deploy to gh-pages
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git fetch origin gh-pages || true
      git checkout -B gh-pages origin/gh-pages || git checkout -B gh-pages
      mkdir -p .
      cp -r site/* .
      touch .nojekyll
      git add -A
      if git diff --cached --quiet; then
        echo "No changes to commit"
      else
        git commit -m "Update alerts.kml $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        git push origin gh-pages
      fi
